"use client";

import { useRef, useEffect } from "react";
import { motion, useInView, useMotionValue, useTransform, animate } from "framer-motion";
import { METRICS } from "@/lib/metrics";

interface Metric {
  label: string;
  value: number;
  suffix: string;
  description: string;
  delay: number;
}

function AnimatedMetric({ label, value, suffix, description, delay }: Metric) {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, margin: "-60px" });
  const count = useMotionValue(0);
  const rounded = useTransform(count, (v) => Math.round(v));

  useEffect(() => {
    if (!inView) return;
    animate(count, value, { delay, duration: 1.6, ease: [0.16, 1, 0.3, 1] });
  }, [inView, value, delay, count]);

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 24 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ delay, duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
      className="rounded-[10px] border border-[var(--border-default)] bg-[var(--bg-surface)] p-7"
    >
      <div className="mb-2 flex items-baseline gap-0.5">
        <motion.span className="font-display text-[40px] font-extrabold tracking-[-0.03em] text-[var(--text-primary)]">
          {rounded}
        </motion.span>
        {suffix && (
          <span className="font-mono text-lg font-medium text-[var(--teal)]">{suffix}</span>
        )}
      </div>
      <p className="m-0 mb-1 text-sm font-semibold text-[var(--text-secondary)]">{label}</p>
      <p className="m-0 text-xs leading-snug text-[var(--text-muted)]">{description}</p>
    </motion.div>
  );
}

export function EvalMetrics() {
  const metrics: Metric[] = [
    {
      label: "Questions evaluated",
      value: METRICS.questions,
      suffix: "",
      description: "Across clinical eval harness",
      delay: 0,
    },
    {
      label: "Keyword match rate",
      value: METRICS.keywordMatchNum,
      suffix: "%",
      description: "Answer grounding vs expected",
      delay: 0.08,
    },
    {
      label: "Average confidence",
      value: METRICS.avgConfidenceNum,
      suffix: "%",
      description: "Mean deterministic score",
      delay: 0.16,
    },
    {
      label: "Flag rate",
      value: parseInt(METRICS.flagRate, 10) || 60,
      suffix: "%",
      description: "Out-of-scope correctly escalated",
      delay: 0.24,
    },
  ];

  return (
    <section id="metrics" className="mx-auto max-w-[1100px] px-10 py-24">
      <div className="mb-14 text-center">
        <span className="font-mono text-[11px] uppercase tracking-[0.1em] text-[var(--teal)]">
          Reproducible evaluation
        </span>
        <h2 className="mt-3 font-display text-[40px] font-extrabold tracking-[-0.03em] text-[var(--text-primary)]">
          Numbers you can check
        </h2>
      </div>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {metrics.map((m) => (
          <AnimatedMetric key={m.label} {...m} />
        ))}
      </div>
      <p className="mt-6 text-center text-[13px] leading-relaxed text-[var(--text-muted)]">
        Generated by{" "}
        <code className="font-mono text-xs text-[var(--text-secondary)]">scripts/run_eval.py</code>{" "}
        over {METRICS.questions} questions. {METRICS.note}
      </p>
    </section>
  );
}
